### PR TITLE
Fix audio issue

### LINKED ISSUE #13: Did you get audio working?
I followed your lead and published my [GL72M 7RDX build to GitHub](https://github.com/jbwharris/hackintosh-msi-GL72M-7RDX) and I thought I would see if my build might be any help for getting your audio working. I wrestled with it for quite awhile, but was able to get it working using AppleHDA Patcher 1.9. I had a little bit of instruction in my readme about it.

### PR DESCRIPTION
**Pull request by rlindsberg**
closes #13

### CODE REVIEW

**Comment by jbwharris** [comment]
Have you tested HDMI audio yet? I can see Hackintool identifies that I have HDMI audio, but it doesn't seem to work when I test the code it outputs.

**Comment by rlindsberg** [comment]
I just tested it and sadly it doesn't work.. The controller is not even detected in Hackintool
Screen Shot 2019-04-24 at 12 18 01 AM

**Comment by jbwharris** [comment]
So I had a big regression on my end, as I updated to 10.14.4 and started having random shutdowns, so I just nuked it and reverted back to 10.14.3. Now where I was seeing that HDMI audio entry was in 10.14.4, but I'm not seeing it now. I had done all my kext updates, so I'm wondering whether there's something in there that got the HDMI audio entry to show up in Hackintool, but I wasn't able to actually get it implemented. I'll have to give it another try later this week.

**Comment by rlindsberg** [comment]
Sorry for the delay, I am doing my thesis project and totally forgot to reply you..

> So I had a big regression on my end, as I updated to 10.14.4 and started having random shutdowns

So weird that you get random shutdowns.. I have heard that it has been very smooth for people to upgrade to 14.4.

> I really don't know how HDMI audio works, for me I have to set layout = 0 and reboot, and set layout to 98 and reboot. If I am lucky then the audio works, HDMI audio disappears. Otherwise I have to do the whole drill :see_no_evil: again

BTW, have you tried fix it this week yet?

**Comment by rlindsberg** [comment]
Sorry for the delay, I am doing my thesis project and totally forgot to reply you..

> So I had a big regression on my end, as I updated to 10.14.4 and started having random shutdowns

So weird that you get random shutdowns.. I have heard that it has been very smooth for people to upgrade to 14.4.

> got the HDMI audio entry to show up in Hackintool

I really don't know how HDMI audio works, for me I have to set layout = 0 and reboot, and set layout to 98 and reboot. If I am lucky then the audio works, HDMI audio disappears. Otherwise I have to do the whole drill :see_no_evil: again

BTW, have you tried fix it this week yet?

**Comment by jbwharris** [comment]
I haven't had a chance yet. I suspect the reason might have been too much, too fast as I did the update, then a flurry of kext updates all in the same spell without testing stability. Obviously if it starts to work as normal you don't tend to question it until the random restarts begin.

**Comment by rlindsberg** [comment]
That's a good point there!

**Pull request merged**
